license = "MIT"
repository = "https://github.com/ernisto/luau-create"
private = false
name = "ernisto/luau_create"
version = "0.1.0"
authors = [
    "ernisto <joaovitordesouza707@gmail.com>",
    "david lagos <davidlagos929@gmail.com>"
]
includes = ["pesde.toml", "README.md", "LICENSE", "docs/**/*.md", "cli/**"]

[dependencies]
semver = {name = "0x5eal/semver", target = "luau", version = "^0.1.1"}

[dev_dependencies]
stylua = {index = "default", name = "pesde/stylua", target = "lune", version = "1.20.3"}

[engines]
lune = "0.9.2"
pesde = "^0.6.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
bin = "cli"
environment = "lune"
build_files = []
scripts = []