name = "ernisto/luau_create"
version = "0.1.0"
license = "MIT"
private = false
repository = "https://github.com/ernisto/luau-create"
includes = ["pesde.toml", "README.md", "LICENSE", "docs/**/*.md", "cli/**"]
authors = [
    "ernisto <joaovitordesouza707@gmail.com>",
    "david lagos <davidlagos929@gmail.com>"
]

[target]
bin = "cli"
environment = "lune"

[engines]
lune = "^0.10.2"
pesde = "^0.7.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
semver = {name = "ernisto/semver", target = "luau", version = "^0.1.2"}
